### ISSUE TITLE
Relatório - P. 2

### ISSUE THREAD

**Issue by thaisbtoscano** [Mutirao/Finatec-UNB#21]
Relatório com narrativa de entregas Juventude e PPA. Deve conter os links das entregas.

**Comment by ClarisCaval** [comment]
Aqui o link do relatório entregue:

https://docs.google.com/document/d/1rlNeWkaKea6GuDXwHYlE1lg2BfVM9kDW1gZkohv_jfE/edit?usp=drive_link
