### ISSUE TITLE
Alinhamento com time UNB para definição do plano de trabalho

### ISSUE THREAD

**Issue by edmirandajr** [Mutirao/Finatec-UNB#5]
Definir etapas e elementos específicos necessários para a produção do Plano de trabalho com as principais entregas de artefatos de documentação do caso de uso no PPA para a UNB/Presidência.

Link para a proposta [Proposta PPA UNB/Presidência](https://docs.google.com/document/d/1WjXvcU5DlN-f8I9ZklRW_AAfBGuU7E27b9-jxaNblV8/edit)

Quais as expectativas da equipe da UNB/Presidência para a entrega do Plano de trabalho?

**Comment by uira** [comment]
Reuniões realizadas com sucesso.
