### ISSUE TITLE
Sistematizar plano de trabalho em formato de relatório

### ISSUE THREAD

**Issue by uira** [Mutirao/Finatec-UNB#6]
- [x] #7
- [x] #8
- [x] Sistematização estruturada de Arquitetura de Informações para Entregas
- [x] #9
- [x] Atualizar board do github de acordo com as demandas da arquitetura proposta.
- [x] #10

**Comment by edmirandajr** [comment]
[[Mutirão Produto01.2023] Plano de trabalho PPA Participativo - Finatec_UNB.pdf](https://github.com/Mutirao/Finatec-UNB/files/12440404/Mutirao.Produto01.2023.Plano.de.trabalho.PPA.Participativo.-.Finatec_UNB.pdf)

**Comment by edmirandajr** [comment]
[[Mutirão Produto01.2023] Plano de trabalho PPA Participativo - Finatec_UNB.pdf](https://github.com/Mutirao/Finatec-UNB/files/12440422/Mutirao.Produto01.2023.Plano.de.trabalho.PPA.Participativo.-.Finatec_UNB.pdf)
